package net.sagberg.tournarrat.ui

object UiTags {
    const val OnboardingNextButton = "onboarding_next_button"
    const val OnboardingFinishButton = "onboarding_finish_button"
    const val TabHome = "tab_home"
    const val TabHistory = "tab_history"
    const val TabSettings = "tab_settings"
    const val HomeScreen = "home_screen"
    const val HistoryScreen = "history_screen"
    const val SettingsScreen = "settings_screen"
    const val DetailScreen = "detail_screen"
    const val HomeGenerateInsightButton = "home_generate_insight_button"
    const val HomeOverflowButton = "home_overflow_button"
    const val HomeDiagnosticsMenuItem = "home_diagnostics_menu_item"
    const val HomeDiagnosticsSheet = "home_diagnostics_sheet"
    const val HomeMapHero = "home_map_hero"
    const val HomeMapFallback = "home_map_fallback"
    const val HomeModeLive = "home_mode_live"
    const val HomeModePopups = "home_mode_popups"
    const val HomeInsightSheet = "home_insight_sheet"
    const val InsightCard = "insight_card"
    const val InsightOpenDetailButton = "insight_open_detail_button"
    const val SettingsSpeechLocaleField = "settings_speech_locale_field"
}
